# theme: jekyll-theme-cayman
theme: jekyll-theme-hacker
github:
  is_project_page: false
logo: /images/logo.png


# Slate – Professional and sleek.
# Hacker – Dark, developer-focused style.
# Midnight – Dark theme for blogs.
# Leap Day – Bright and colorful.
# Dinky – Compact and minimalistic.